
python:
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
   - os: windows
     python:
         - "3.3"
         - "3.4"
         - "3.5"
   - os: linux
     sudo: required
     python:
             - "3.3"
             - "3.4"
             - "3.5"
    
before_install:
- sudo apt-get update
- sudo apt-get install python3

#install: pythen3 setup.py install
script: "python tools.py"
