language: python 

python:
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  allow_failures:
    - python: "2.7"
  include:
 
   - os: linux
     sudo: required

before_install:
#- sudo apt-get update
- chmod +x setup.py
#- sudo apt-get install python3

install: 
 - python setup.py install
 - python3 setup.py install
script: 
 - exit 0
