
python:
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
   - os: windows
     python:
         - "3.3"
         - "3.4"
         - "3.5"
   - os: linux
     sudo: required
     python:
             - "3.3"
             - "3.4"
             - "3.5"
    
#install: python3 setup.py install
script: trial tools
